version: '3.9'
services:
  traefik:
    image: "traefik:v2.6"
    volumes:
      - "./traefik:/etc/traefik"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - 8080:8080
      - 443:443
      - 80:80
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:10002"]
        interval: 15s
        timeout: 10s
        retries: 5
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    image: timesheets_api
    ports:
      - 5111:5111
    restart: on-failure
    depends_on:
      - azurite
    links:
      - azurite